import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import About from "@/components/About";

const inter = Inter({ subsets: ["latin"] });
const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", recursive.className, inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          themes={["dark", "light"]}
        >
          <Navbar />
          {children}
          {/* <About /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
